FROM python:3.7-stretch
RUN apt-get update
RUN apt-get install -y apt-utils supervisor python3 python3-dev default-libmysqlclient-dev build-essential unixodbc unixodbc-dev apache2 apache2-utils apache2-dev libapache2-mod-wsgi-py3
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir -p /etc/letsencrypt/live/localhost
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/letsencrypt/live/localhost/privkey.pem \
    -out /etc/letsencrypt/live/localhost/fullchain.pem \
    -subj /CN=localhost
WORKDIR "/home/eatfit/eatfitrepo/EatFitService"
COPY . .
ADD ./000-default-le-ssl.conf /etc/apache2/sites-enabled/000-default-le-ssl.conf
ADD ./000-default.conf /etc/apache2/sites-enabled/000-default.conf
ADD ./options-ssl-apache.conf /etc/letsencrypt/options-ssl-apache.conf
ADD ./modules.load /etc/apache2/mods-enabled/modules.load
ADD ./EatFitService-celery.conf /etc/supervisor/conf.d/EatFitService-celery.conf
RUN pip install virtualenv
RUN python -m virtualenv /env
RUN . /env/bin/activate && pip install -r requirements.txt
RUN chown -R www-data:www-data /home/eatfit/eatfitrepo/EatFitService
RUN chmod 775 -R /home/eatfit/eatfitrepo/EatFitService
RUN touch /var/log/nutrition-service.log
RUN chmod 777 /var/log/nutrition-service.log
