# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LmpCategory',
            fields=[
                ('lmp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lmp_category',
            },
        ),
        migrations.CreateModel(
            name='NutritionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nutrition_attribute',
            },
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('combined_amount_and_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_percent', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nutrition_fact',
            },
        ),
        migrations.CreateModel(
            name='NutritionGroupAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nutrition_group_attribute',
            },
        ),
        migrations.CreateModel(
            name='NutritionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrition_label',
            },
        ),
        migrations.CreateModel(
            name='NwdMainCategory',
            fields=[
                ('nwd_main_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.LmpCategory')),
            ],
            options={
                'db_table': 'nwd_main_category',
            },
        ),
        migrations.CreateModel(
            name='NwdMainCategoryMinNutritionFactDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_absolute', models.FloatField(blank=True, null=True)),
                ('min_relative', models.IntegerField(blank=True, null=True)),
                ('nutrition_fact_canonical_name', models.CharField(max_length=255)),
                ('nwd_main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NwdMainCategory')),
            ],
            options={
                'db_table': 'nwd_main_category_min_nutrition_fact_difference',
            },
        ),
        migrations.CreateModel(
            name='NwdSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nwd_subcategory_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('lmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.LmpCategory')),
                ('nwd_main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NwdMainCategory')),
            ],
            options={
                'db_table': 'nwd_subcategory',
            },
        ),
        migrations.CreateModel(
            name='NwdSubcategoryMinNutritionFactDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_absolute', models.FloatField(blank=True, null=True)),
                ('min_relative', models.IntegerField(blank=True, null=True)),
                ('nutrition_fact_canonical_name', models.CharField(max_length=255)),
                ('nwd_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NwdSubcategory')),
            ],
            options={
                'db_table': 'nwd_subcategory_min_nutrition_fact_difference',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_market_country_code', models.SmallIntegerField(blank=True, null=True)),
                ('gln', models.BigIntegerField(blank=True, null=True)),
                ('gtin', models.BigIntegerField()),
                ('status', models.BigIntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_name',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TrustBoxAPI.Product')),
            ],
            options={
                'db_table': 'nutrition',
            },
        ),
        migrations.AddField(
            model_name='productname',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.Product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='nwd_main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NwdMainCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='nwd_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NwdSubcategory'),
        ),
        migrations.CreateModel(
            name='NutritionFactsGroup',
            fields=[
                ('nutrition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TrustBoxAPI.Nutrition')),
            ],
            options={
                'db_table': 'nutrition_facts_group',
            },
        ),
        migrations.AddField(
            model_name='nutritionlabel',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.Nutrition'),
        ),
        migrations.AddField(
            model_name='nutritionattribute',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.Nutrition'),
        ),
        migrations.AddField(
            model_name='nutritiongroupattribute',
            name='nutrition_facts_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NutritionFactsGroup'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='nutrition_facts_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NutritionFactsGroup'),
        ),
    ]
