# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
