# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0002_auto_20160516_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('agreed_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.Product')),
            ],
            options={
                'db_table': 'agreed_data',
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_timestamp', models.DateTimeField()),
                ('successful', models.BooleanField()),
            ],
            options={
                'db_table': 'import_log',
            },
        ),
    ]
