# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0003_agreeddata_importlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='failed_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
