# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0006_auto_20160519_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nwdmaincategory',
            name='lmp',
        ),
    ]
