# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0007_remove_nwdmaincategory_lmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionattribute',
            name='canonical_name',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionattribute',
            name='value',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfact',
            name='canonical_name',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritiongroupattribute',
            name='value',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlabel',
            name='value',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='productname',
            name='name',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
