# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0009_importlog_product_gtin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingTrustboxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('total_weight', models.FloatField(verbose_name='Gesamtgewicht')),
                ('gtin', models.BigIntegerField(verbose_name='GTIN')),
                ('serving_size', models.FloatField(verbose_name='Serving Size')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('salt', models.FloatField(verbose_name='Salz')),
                ('sodium', models.FloatField(verbose_name='Natrium')),
                ('energy', models.FloatField(verbose_name='Energie')),
                ('fat', models.FloatField(verbose_name='Fett')),
                ('saturated_fat', models.FloatField(verbose_name='Ges\xe4tigtes Fett')),
                ('carbohydrate', models.FloatField(verbose_name='Kohlenhydrate')),
                ('sugar', models.FloatField(verbose_name='davon Zucker')),
                ('fibers', models.FloatField(verbose_name='Ballaststoffe')),
                ('protein', models.FloatField(verbose_name='Protein')),
                ('nwd_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TrustBoxAPI.NwdSubcategory', verbose_name='Kategorie')),
            ],
            options={
                'db_table': 'missing_trustbox_item',
            },
        ),
    ]
