# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0010_missingtrustboxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingtrustboxitem',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Preis in CHF'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='carbohydrate',
            field=models.FloatField(verbose_name='Kohlenhydrate pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='energy',
            field=models.FloatField(verbose_name='Energie pro 100g in KJ'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='fat',
            field=models.FloatField(verbose_name='Fett pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='fibers',
            field=models.FloatField(verbose_name='Ballaststoffe pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='protein',
            field=models.FloatField(verbose_name='Protein pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='salt',
            field=models.FloatField(verbose_name='Salz pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='saturated_fat',
            field=models.FloatField(verbose_name='Ges\xe4ttigtes Fett pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='sodium',
            field=models.FloatField(verbose_name='Natrium pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='sugar',
            field=models.FloatField(verbose_name='davon Zucker pro 100g in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='total_weight',
            field=models.FloatField(verbose_name='Gesamtgewicht in Gramm'),
        ),
    ]
