# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0011_auto_20160711_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='nwdsubcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/subcategory_icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='carbohydrate',
            field=models.FloatField(verbose_name='Kohlenhydrate pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='energy',
            field=models.FloatField(verbose_name='Energie pro 100g/ml in KJ'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='fat',
            field=models.FloatField(verbose_name='Fett pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='fibers',
            field=models.FloatField(verbose_name='Ballaststoffe pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='protein',
            field=models.FloatField(verbose_name='Protein pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='salt',
            field=models.FloatField(verbose_name='Salz pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='saturated_fat',
            field=models.FloatField(verbose_name='Ges\xe4ttigtes Fett pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='sodium',
            field=models.FloatField(verbose_name='Natrium pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='missingtrustboxitem',
            name='sugar',
            field=models.FloatField(verbose_name='davon Zucker pro 100g/ml in Gramm'),
        ),
    ]
