# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustBoxAPI', '0012_auto_20160826_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwdsubcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_icons', verbose_name='Icon'),
        ),
    ]
