# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'minor_category_icons', verbose_name=b'Icon'),
        ),
        migrations.AddField(
            model_name='minorcategory',
            name='nwd_subcategory_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
