# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('import_started', models.DateTimeField()),
                ('import_finished', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_log',
            },
        ),
    ]
