# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0002_auto_20171223_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ofcom_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='NutritionService.Product'),
        ),
        migrations.AlterField(
            model_name='nutritionfact',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='NutritionService.Product'),
        ),
    ]
