# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 14:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0003_auto_20180127_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='health_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Fruit, Vegetable, Nuts Share'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, choices=[('Trustbox', 'Trustbox'), ('Crowdsourcing', 'Crowdsourcing'), ('Openfood', 'Openfood')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_checked',
            field=models.BooleanField(default=False),
        ),
    ]
