# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0004_auto_20180515_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reporting_app', models.CharField(blank=True, max_length=256, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'error_log',
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, choices=[('Trustbox', 'Trustbox'), ('Crowdsourcing', 'Crowdsourcing'), ('Openfood', 'Openfood'), ('Codecheck', 'Codecheck'), ('Auto-ID Labs', 'Auto-ID Labs')], max_length=256, null=True),
        ),
    ]
