# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0006_crowdsourceproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourceproduct',
            name='major_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NutritionService.MajorCategory'),
        ),
        migrations.AlterField(
            model_name='crowdsourceproduct',
            name='minor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NutritionService.MinorCategory'),
        ),
    ]
