# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0007_auto_20180515_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourceproduct',
            name='ingredient_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crowdsourceproduct',
            name='ingredient_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crowdsourceproduct',
            name='ingredient_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crowdsourceproduct',
            name='ingredient_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
