# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-29 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0008_auto_20180516_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfoundlog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
