# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0009_notfoundlog_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_de', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_fr', models.TextField(blank=True, null=True)),
                ('text_it', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_tipp_images')),
                ('minor_categories', models.ManyToManyField(blank=True, related_name='minor_category', to='NutritionService.MinorCategory')),
            ],
            options={
                'db_table': 'health_tipp',
                'verbose_name': 'Health Tipp',
                'verbose_name_plural': 'Health Tipps',
            },
        ),
        migrations.CreateModel(
            name='NutrientName',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'db_table': 'nutrient_name',
                'verbose_name': 'Nutrient Name',
                'verbose_name_plural': 'Nutrient Names',
            },
        ),
        migrations.AddField(
            model_name='healthtipp',
            name='nutrients',
            field=models.ManyToManyField(blank=True, related_name='nutrients', to='NutritionService.NutrientName'),
        ),
    ]
