# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0010_auto_20180620_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majorcategory',
            old_name='description',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='minorcategory',
            old_name='description',
            new_name='name_de',
        ),
    ]
