# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0011_auto_20180620_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorcategory',
            name='canonical_name',
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='name_en',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='name_fr',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='name_it',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='minorcategory',
            name='name_en',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='minorcategory',
            name='name_fr',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='minorcategory',
            name='name_it',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
