# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-30 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0012_auto_20180620_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='automatic_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.BigIntegerField(unique=True),
        ),
    ]
