# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0013_auto_20180630_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ofcom_value',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
