# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0014_auto_20180704_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='found_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='major_category',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NutritionService.MajorCategory'),
        ),
    ]
