# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0015_auto_20180728_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, choices=[('Trustbox', 'Trustbox'), ('Crowdsourcing', 'Crowdsourcing'), ('Openfood', 'Openfood'), ('Codecheck', 'Codecheck'), ('open_world', 'open_world'), ('Auto-ID Labs', 'Auto-ID Labs')], max_length=256, null=True),
        ),
    ]
