# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-10 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('NutritionService', '0018_remove_product_weighted_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_unit', models.CharField(max_length=255)),
                ('receipt_id', models.CharField(max_length=255)),
                ('article_id', models.CharField(max_length=255)),
                ('article_type', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('quantity_unit', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('price_currency', models.CharField(max_length=255)),
                ('receipt_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'digital_receipt',
                'verbose_name': 'DigitalReceipt',
                'verbose_name_plural': 'DigitalReceipts',
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=255)),
                ('article_type', models.CharField(max_length=255)),
                ('gtin', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'matching',
                'verbose_name': 'Matching',
                'verbose_name_plural': 'Matchings',
            },
        ),
        migrations.CreateModel(
            name='ReceiptToNutritionPartner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'receipt_to_nutrition_partner',
                'verbose_name': 'ReceiptToNutritionPartner',
                'verbose_name_plural': 'ReceiptToNutritionPartners',
            },
        ),
        migrations.CreateModel(
            name='ReceiptToNutritionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2n_username', models.CharField(max_length=255)),
                ('r2n_user_active', models.BooleanField(default=True)),
                ('r2n_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionService.ReceiptToNutritionPartner')),
            ],
            options={
                'db_table': 'receipt_to_nutrition_user',
                'verbose_name': 'ReceiptToNutritionUser',
                'verbose_name_plural': 'ReceiptToNutritionUsers',
            },
        ),
        migrations.AddField(
            model_name='digitalreceipt',
            name='r2n_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionService.ReceiptToNutritionUser'),
        ),
        migrations.AlterUniqueTogether(
            name='receipttonutritionuser',
            unique_together=set([('r2n_partner', 'r2n_username')]),
        ),
        migrations.AlterUniqueTogether(
            name='digitalreceipt',
            unique_together=set([('r2n_user', 'business_unit', 'receipt_id')]),
        ),
    ]
