# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-10 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0019_auto_20181110_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digitalreceipt',
            unique_together=set([]),
        ),
    ]
