# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-10 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0021_auto_20181118_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFoundMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=255)),
                ('article_type', models.CharField(max_length=255)),
                ('business_unit', models.CharField(max_length=255)),
                ('price_per_unit', models.FloatField()),
                ('counter', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'db_table': 'non_found_matching',
                'verbose_name': 'NonFoundMatching',
                'verbose_name_plural': 'NonFoundMatchings',
            },
        ),
        migrations.AlterField(
            model_name='matching',
            name='eatfit_product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NutritionService.Product'),
        ),
    ]
