# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0022_auto_20190110_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAtRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatfit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionService.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_id', models.CharField(max_length=255, unique=True)),
                ('retailer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='productatretailer',
            name='retailer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionService.Retailers', to_field=b'retailer_id'),
        ),
    ]
