# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-14 10:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0023_auto_20190224_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'product_images')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_image', to='NutritionService.Product')),
            ],
            options={
                'db_table': 'additional_image',
                'verbose_name': 'Additional Image',
                'verbose_name_plural': 'Additional Images',
            },
        ),
        migrations.CreateModel(
            name='MarketRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_region_code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message=b'Invalid ID pattern (Format: CH)', regex=b'^[A-Z]{2}$')])),
                ('market_region_name', models.CharField(blank=True, choices=[(b'Switzerland', b'Switzerland'), (b'Germany', b'Germany'), (b'Austria', b'Austria'), (b'France', b'France'), (b'Italy', b'Italy')], max_length=52, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_region', to='NutritionService.Product')),
            ],
            options={
                'db_table': 'market_regions',
                'verbose_name': 'Market Region',
                'verbose_name_plural': 'Market Regions',
            },
        ),
        migrations.CreateModel(
            name='ProductInMarketRegionAtRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NutritionService.MarketRegion', to_field=b'market_region_code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionService.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_code', models.CharField(max_length=52, unique=True, validators=[django.core.validators.RegexValidator(message=b'Invalid ID pattern (Format: ch.coop)', regex=b'^[\\w]{2}\\.[\\w\\d-_]+$')])),
                ('retailer_name', models.CharField(choices=[(b'Migros', b'Migros'), (b'Coop', b'Coop'), (b'Farmy', b'Farmy'), (b'Volg', b'Volg'), (b'Edeka', b'Edeka')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='NutritionService.Product')),
            ],
            options={
                'db_table': 'retailers',
                'verbose_name': 'Retailer',
                'verbose_name_plural': 'Retailers',
            },
        ),
        migrations.AddField(
            model_name='productinmarketregionatretailer',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NutritionService.Retailer', to_field=b'retailer_code'),
        ),
    ]
