# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0023_auto_20190208_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_region_id', models.CharField(max_length=255, unique=True)),
                ('market_region_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'retailers',
                'verbose_name': 'Market Region',
                'verbose_name_plural': 'Market Regions',
            },
        ),
        migrations.CreateModel(
            name='ProductInMarketRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatfit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionService.Product')),
                ('market_region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionService.MarketRegion', to_field=b'market_region_id')),
            ],
        ),
        migrations.AlterModelOptions(
            name='retailers',
            options={'verbose_name': 'Retailers', 'verbose_name_plural': 'Retailers'},
        ),
        migrations.AlterModelTable(
            name='retailers',
            table='retailers',
        ),
    ]
