# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-28 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0024_auto_20190208_1451'),
        ('NutritionService', '0023_auto_20190228_1251'),
    ]

    operations = [
    ]
