# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-06 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0025_merge_20190228_1252'),
        ('NutritionService', '0023_auto_20190224_1037'),
    ]

    operations = [
    ]
