# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-01 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0025_importerrorlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinmarketregionatretailer',
            name='market_region',
        ),
        migrations.RemoveField(
            model_name='productinmarketregionatretailer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinmarketregionatretailer',
            name='retailer',
        ),
        migrations.RemoveField(
            model_name='marketregion',
            name='market_region_code',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='retailer_code',
        ),
        migrations.DeleteModel(
            name='ProductInMarketRegionAtRetailer',
        ),
    ]
