# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0027_auto_20190401_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketregion',
            name='product',
        ),
        migrations.AddField(
            model_name='retailer',
            name='market_region_name',
            field=models.CharField(choices=[('Switzerland', 'Switzerland'), ('Germany', 'Germany'), ('Austria', 'Austria'), ('France', 'France'), ('Italy', 'Italy')], default='Switzerland', max_length=52),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MarketRegion',
        ),
    ]
