# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0028_auto_20190403_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='certainty',
            new_name='certainity',
        ),
    ]
