# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0029_auto_20190403_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_region_name', models.CharField(choices=[(b'Switzerland', b'Switzerland'), (b'Germany', b'Germany'), (b'Austria', b'Austria'), (b'France', b'France'), (b'Italy', b'Italy')], max_length=52)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_region', to='NutritionService.Product')),
            ],
            options={
                'db_table': 'market_region',
                'verbose_name': 'Market Region',
                'verbose_name_plural': 'Market Regions',
            },
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='market_region_name',
        ),
        migrations.AlterField(
            model_name='retailer',
            name='retailer_name',
            field=models.CharField(choices=[(b'Migros', b'Migros'), (b'Coop', b'Coop'), (b'Denner', b'Denner'), (b'Farmy', b'Farmy'), (b'Volg', b'Volg'), (b'Edeka', b'Edeka')], max_length=20),
        ),
    ]
