# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0030_auto_20190404_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='certainity',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false'), ('mayContain', 'mayContain')], max_length=11, null=True),
        ),
    ]
