# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-20 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0032_nutritionfact_is_mixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NutritionService.MinorCategory'),
        ),
    ]
