# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-19 05:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0033_auto_20190820_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutriScoreFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fvpn_total_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fvpn_total_percentage_estimated', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('vegetable_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('vegetable_percentage_dried', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('nuts_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ofcom_n_energy_kj', models.FloatField(blank=True, null=True)),
                ('ofcom_n_saturated_fat', models.FloatField(blank=True, null=True)),
                ('ofcom_n_sugars', models.FloatField(blank=True, null=True)),
                ('ofcom_n_salt', models.FloatField(blank=True, null=True)),
                ('ofcom_p_protein', models.FloatField(blank=True, null=True)),
                ('ofcom_p_fvpn', models.FloatField(blank=True, null=True)),
                ('ofcom_p_dietary_fiber', models.FloatField(blank=True, null=True)),
                ('ofcom_n_energy_kj_mixed', models.FloatField(blank=True, null=True)),
                ('ofcom_n_saturated_fat_mixed', models.FloatField(blank=True, null=True)),
                ('ofcom_n_sugars_mixed', models.FloatField(blank=True, null=True)),
                ('ofcom_n_salt_mixed', models.FloatField(blank=True, null=True)),
                ('ofcom_p_protein_mixed', models.FloatField(blank=True, null=True)),
                ('ofcom_p_fvpn_mixed', models.FloatField(blank=True, null=True)),
                ('ofcom_p_dietary_fiber_mixed', models.FloatField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_score_fact', to='NutritionService.Product')),
            ],
            options={
                'db_table': 'nutri_score_fact',
                'verbose_name': 'Nutri-Score Facts',
                'verbose_name_plural': 'Nutri-Score Facts',
            },
        ),
    ]
