# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0034_nutriscorefacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriscorefacts',
            name='pulses_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='nutriscorefacts',
            name='pulses_percentage_dried',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
