# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0035_auto_20190926_1352'),
        ('NutritionService', '0035_auto_20190926_1358'),
    ]

    operations = [
    ]
