# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0037_auto_20191003_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutri_score_number_of_errors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
