# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0039_auto_20191010_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='major_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NutritionService.MajorCategory'),
        ),
    ]
