    # -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0040_auto_20191010_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriscorefacts',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_score_facts', to='NutritionService.Product'),
        ),
    ]
