# Generated by Django 2.1 on 2019-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0041_auto_20191011_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourceproduct',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Gesättigtes Fett pro 100g/ml in Gramm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
