# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0042_auto_20200203_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstudies',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
