# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-03 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0043_currentstudies_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstudies',
            name='link',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
