# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-04 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0044_auto_20200203_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstudies',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
