# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0046_matching_price_per_unit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matching',
            index=models.Index(fields=['article_type', 'article_id'], name='matching_article_00b3b1_idx'),
        ),
    ]
