# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gtin', models.BigIntegerField()),
                ('reebate_name', models.CharField(max_length=255)),
                ('salt', models.FloatField()),
                ('language_code', models.CharField(default=b'de', max_length=255)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
    ]
