# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salttrackeruser',
            name='cumulus_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salttrackeruser',
            name='cumulus_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
