# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160605_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecord',
            name='added',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
