# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodrecord_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('weeks', models.IntegerField(default=2)),
                ('min_records_per_week', models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Study'),
        ),
    ]
