# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160608_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_locked', models.BooleanField(default=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Study')),
            ],
            options={
                'db_table': 'study_day',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='foodrecord',
            name='added',
        ),
        migrations.RemoveField(
            model_name='foodrecord',
            name='study',
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='study_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.StudyDay'),
        ),
    ]
