# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160609_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='study',
            table='study',
        ),
    ]
