# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160609_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecord',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
