# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160705_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reebatecredentials',
            name='last_reebate_import',
        ),
    ]
