# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_reebatecredentials_last_reebate_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='reebatecredentials',
            name='last_reebate_import',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
