# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reebatecredentials_last_reebate_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrositem',
            name='gtin',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
