# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160705_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrosbasket',
            name='added_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
