# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_migrosbasket_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salttrackeruser',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
