# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_migrositem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='kalium',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
