# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160719_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
