# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_auto_20160720_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.BigIntegerField()),
                ('purchased', models.DateTimeField()),
                ('total_salt', models.FloatField()),
                ('quantity', models.FloatField()),
                ('added', models.DateTimeField()),
                ('nwd_subcategory_name', models.TextField(blank=True, max_length=1024, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
