# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_shoppingresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingresult',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='shoppingresult',
            table='shopping_result',
        ),
    ]
