# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20160723_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='tooltip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
