# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20160729_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingresult',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingresult',
            name='total_sugar',
            field=models.FloatField(default=0),
        ),
    ]
