# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160801_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingresult',
            name='serving_size',
            field=models.FloatField(default=0),
        ),
    ]
