# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_shoppingresult_serving_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('nwd_subcategory_name', models.TextField(blank=True, max_length=1024, null=True)),
                ('category_color', models.CharField(max_length=255)),
                ('is_general', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'media/shopping_tips')),
            ],
            options={
                'db_table': 'shopping_tip',
                'managed': True,
            },
        ),
    ]
