# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_shoppingtip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingtip',
            name='category_color',
            field=models.CharField(max_length=255, verbose_name=b'Kategoriefarbe'),
        ),
        migrations.AlterField(
            model_name='shoppingtip',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'shopping_tips', verbose_name=b'Icon'),
        ),
        migrations.AlterField(
            model_name='shoppingtip',
            name='is_general',
            field=models.BooleanField(default=False, verbose_name=b'Allgemeiner Tipp'),
        ),
        migrations.AlterField(
            model_name='shoppingtip',
            name='nwd_subcategory_name',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name=b'(Sub-)Kategoriename'),
        ),
        migrations.AlterField(
            model_name='shoppingtip',
            name='text',
            field=models.TextField(verbose_name=b'Text'),
        ),
    ]
