# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20160806_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('unit', models.CharField(max_length=255)),
                ('salt', models.FloatField()),
                ('kalium', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_item_supplement',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='supplements',
            field=models.ManyToManyField(to='api.FoodItemSupplement'),
        ),
    ]
