# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20160817_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemsupplement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
