# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20160906_1534'),
    ]

    operations = [

        migrations.AddField(
            model_name='foodrecord',
            name='added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
