# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20160920_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
