# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20161231_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='unit_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='unit_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='unit_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='unit_it',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
