# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20161231_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'category_icons', verbose_name=b'Icon'),
        ),
    ]
