# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_category_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='numberOfPortions',
            field=models.FloatField(),
        ),
    ]
