# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20170314_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='red_cap_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooditemsupplement',
            name='red_cap_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
