# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20170604_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemsupplement',
            name='added_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditemsupplement',
            name='alcohol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditemsupplement',
            name='fruit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditemsupplement',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditemsupplement',
            name='vegetables',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='total_added_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='total_alcohol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='total_fruit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='total_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='total_vegetables',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecordsupplement',
            name='total_added_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecordsupplement',
            name='total_alcohol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecordsupplement',
            name='total_fruit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecordsupplement',
            name='total_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodrecordsupplement',
            name='total_vegetables',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
