# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0049_auto_20170604_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trousers_type', models.CharField(blank=True, max_length=50, null=True)),
                ('chest_type', models.CharField(blank=True, max_length=50, null=True)),
                ('head_type', models.CharField(blank=True, max_length=50, null=True)),
                ('eyes_type', models.CharField(blank=True, max_length=50, null=True)),
                ('nose_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_type', models.CharField(blank=True, max_length=50, null=True)),
                ('glasses_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shoes_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'avatar_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvatarMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('ingredient_level', models.IntegerField()),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'avatar_message',
                'managed': True,
            },
        ),
    ]
