# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_avatardata_avatarmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatardata',
            old_name='eyes_type',
            new_name='eyecolor_type',
        ),
        migrations.RenameField(
            model_name='avatardata',
            old_name='trousers_type',
            new_name='outfit_type',
        ),
        migrations.RemoveField(
            model_name='avatardata',
            name='chest_type',
        ),
    ]
