# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20170620_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'avatar_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvatarTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('ingredient_level', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'avatar_tip',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='avatarmessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
