# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_avatarlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatardata',
            name='show_tutorial',
            field=models.BooleanField(default=True),
        ),
    ]
