# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_fooditemsupplement_show_in_foodtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatardata',
            name='beard_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
