# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_avatardata_beard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarmessage',
            name='message_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avatarmessage',
            name='message_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avatarmessage',
            name='message_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avatarmessage',
            name='message_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avatartip',
            name='message_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avatartip',
            name='message_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avatartip',
            name='message_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avatartip',
            name='message_it',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
