# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20170712_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='category',
            name='category_detail_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
