# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20170810_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_detail_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_detail_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_detail_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_detail_text_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
