# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20170810_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='profile_data_type',
            field=models.CharField(choices=[(b'House_Hold_Data', b'House_Hold_Data'), (b'Eating_Habits_Data', b'Eating_Habits_Data'), (b'Shopping_Habits_Data', b'Shopping_Habits_Data'), (b'General', b'General'), (b'Food_Tracker', b'Food_Tracker'), (b'Salt_Tracker', b'Salt_Tracker'), (b'Analysis_Survey', b'Analysis_Survey'), (b'Nutrition_Avatar', b'Nutrition_Avatar')], max_length=255),
        ),
    ]
