# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20170810_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='survey_completed',
            field=models.BooleanField(default=False),
        ),
    ]
